A1/Controllers/MySettingController.cs
using A1.Data;
using Microsoft.AspNetCore.Mvc;

namespace A1.Controllers
{
    public class MySettingController : Controller
    {
        private readonly SaveData _context;

        public MySettingController(SaveData context)
        {
            _context = context;
        }

        public static string Myback = "snow";

        //设定界面
        public IActionResult Setting(string back)
        {
            //back = (Myback == "black") ? "1" : "0";
            if (MyHomePageController.user.Count() == 0)
            {
                return RedirectToAction("LoginPage", "MyHomePage");
            }

            var u = MyHomePageController.user.FirstOrDefault();
            var newuser = _context.UserTable.Where(x => x.Id == u.Id).FirstOrDefault();
            if (back != null)
            {
                //第二次以上
                if (back == "1")
                {
                    ViewBag.MyBackground = "black";
                    Myback = ViewBag.MyBackground;
                }
                else
                {
                    ViewBag.MyBackground = "snow";
                    Myback = ViewBag.MyBackground;
                }
            }
            else
            {
                //一开始 snow
                if (Myback == "black")
                {
                    ViewBag.MyBackground = "black";
                    Myback = ViewBag.MyBackground;
                }
                else
                {
                    ViewBag.MyBackground = "snow";
                    Myback = ViewBag.MyBackground;
                }
            }



            return View(newuser);
        }

        //关于我们
        public IActionResult ContactUs()
        {
            return View();
        }

    }
}

A1/Views/MySetting/ContactUs.cshtml
@{
	ViewData["Title"] = "ContactUs";
	Layout = "ContactUs_Layout";
}

<div class="i_header">

	<div class="bp">
	</div>

</div>

<section class="footer_get_touch_outer">
	<div class="container">
		<div class="footer_get_touch_inner grid-70-30">

			<div class="colmun-70 get_form">
				<div class="get_form_inner">
					<div class="get_form_inner_text">
						<h3>About Us</h3>
					</div>
					<div class="context">
						<div class="f1">
							<p><b>Founder:</b></p>
							<p><b>Date created:</b></p>
							<p><b>Partner:</b></p>
							<p><b>Country:</b></p>
							<p><b>Introduction:</b></p>
						</div>
						<div class="f2">
							<p>Hoo</p>
							<p>2022/7/1</p>
							<p>Dog | Alin | Jack | Yuu</p>
							<p>Malaysia</p>
							<p>This is an online shopping website that allows people to easily buy and shop. We are still working hard to develop and thank you for your use.</p>
						</div>
					</div>
					<div class="grid-full">
						<a asp-area="" asp-controller="MySetting" asp-action="Setting"><input type="button" value="Back"></a>
					</div>
				</div>
			</div>
			<div class="colmun-30 get_say_form">
				<h5>Say Hi!</h5>
				<ul class="get_say_info_sec">
					<li class="n">
						<i class="fa fa-envelope"></i>
						<a href='mailto:wengchin123456@gmail.com' target="_blank">wengchin123456@gmail.com</a>
					</li>
					<li>
						<i class="fa-solid fa-mobile-screen-button"></i>
						<a href='tel:0164486909' target="_blank">+60 0164486909</a>
					</li>
					<li>
						<i class="fa-brands fa-whatsapp"></i>
						<a href='https://web.whatsapp.com/' target="_blank">Whatsapp</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>

A1/Views/MySetting/Setting.cshtml
@model User

@{
	ViewData["Title"] = "Setting";
	Layout = "Setting_Layout";
}

@if (@ViewBag.MyBackground == "black")
{
	<div class="all"></div>
}
else
{
	<div class="wall"></div>
}

<div class="container">
	@if (@ViewBag.MyBackground == "black")
	{
		<div id="myback" class="settings black">
			<div class="head">
				<figure class="photo">
					<img src="~/Img/TX/@Model.Hurl" />
				</figure>
				<div class="user_info">
					<h2>@Model.UserName</h2>
					<small>@Model.Email</small>
				</div>
				<span class="alink close">
					<a asp-area="" asp-controller="MyHomePage" asp-action="Index" style="color:black;"><i class="far fa-times-circle"></i></a>
				</span>
			</div>
			<div class="body">
				<dl class="setting">
					<dd>
						<li class="setting_item">
							<i class="fas fa-moon"></i>
							<span class="item_options">Dark Mode</span>
							<div class="switch">
								@if (@ViewBag.MyBackground == "black")
								{
									<input id="dark_mode" type="checkbox" name="back" checked="checked" onclick="check(false)" />
									<label for="dark_mode"></label>
								}
								else
								{
									<input id="dark_mode" type="checkbox" name="back" onclick="check(true)" />
									<label for="dark_mode"></label>
								}
							</div>
						</li>
						<li class="setting_item h">
							<i class="fa-solid fa-address-book"></i>
							<a asp-area="" asp-controller="MySetting" asp-action="ContactUs" class="item_options b"><span>About us</span></a>
							<span class="alink">
								<i class="fas fa-angle-right"></i>
							</span>
						</li>
						<li class="setting_item h">
							<i class="fas fa-sign-out-alt"></i>
							<a asp-area="" asp-controller="MyHomePage" asp-action="Signoutpage" class="item_options b"><span>Sign out</span></a>
							<span class="alink">
								<i class="fas fa-angle-right"></i>
							</span>
						</li>
						<li class="setting_item h">
							<i class="fa-solid fa-delete-left"></i>
							<a asp-area="" asp-controller="MyHomePage" asp-action="Index" class="item_options b"><span>Back</span></a>
							<span class="alink">
								<i class="fas fa-angle-right"></i>
							</span>
						</li>
					</dd>
				</dl>
			</div>
		</div>
	}
	else
	{
		<div id="myback" class="settings">
			<div class="head">
				<figure class="photo">
					<img src="~/Img/TX/@Model.Hurl" />
				</figure>
				<div class="user_info">
					<h2>@Model.UserName</h2>
					<small>@Model.Email</small>
				</div>
				<span class="alink close">
					<a asp-area="" asp-controller="MyHomePage" asp-action="Index" style="color:white;"><i class="far fa-times-circle"></i></a>
				</span>
			</div>
			<div class="body">
				<dl class="setting">
					<dd>
						<li class="setting_item">
							<i class="fas fa-moon"></i>
							<span class="item_options">Dark Mode</span>
							<div class="switch">
								@if (@ViewBag.MyBackground == "black")
								{
									<input id="dark_mode" type="checkbox" name="back" checked="checked" onclick="check(false)" />
									<label for="dark_mode"></label>
								}
								else
								{
									<input id="dark_mode" type="checkbox" name="back" onclick="check(true)" />
									<label for="dark_mode"></label>
								}
							</div>
						</li>
						<li class="setting_item n">
							<i class="fa-solid fa-address-book"></i>
							<a asp-area="" asp-controller="MySetting" asp-action="ContactUs" class="item_options snow"><span>About us</span></a>
							<span class="alink">
								<i class="fas fa-angle-right"></i>
							</span>
						</li>
						<li class="setting_item n">
							<i class="fas fa-sign-out-alt"></i>
							<a asp-area="" asp-controller="MyHomePage" asp-action="Signoutpage" class="item_options snow"><span>Sign out</span></a>
							<span class="alink">
								<i class="fas fa-angle-right"></i>
							</span>
						</li>
						<li class="setting_item n">
							<i class="fa-solid fa-delete-left"></i>
							<a asp-area="" asp-controller="MyHomePage" asp-action="Index" class="item_options snow"><span>Back</span></a>
							<span class="alink">
								<i class="fas fa-angle-right"></i>
							</span>
						</li>
					</dd>
				</dl>
			</div>
		</div>
	}
</div>

<script>
	function check(v){
		console.log("v  =" +v)
		if(v == true){
			//打开
			document.getElementById("dark_mode").checked = true;
			window.location.href="/MySetting/Setting?back=1";
		}else if(v == false){
			//关掉
			document.getElementById("dark_mode").checked = false;
			window.location.href="/MySetting/Setting?back=0";
		}else{
			if(@ViewBag.MyBackground == "black"){
				document.getElementById("dark_mode").checked = true;
				window.location.href="/MySetting/Setting?back=1";
			}else{
				document.getElementById("dark_mode").checked = false;
				window.location.href="/MySetting/Setting?back=0";
			}
		}
	}
</script>