A1/Controllers/HistoryDetailsController.cs
using A1.Data;
using A1.Models;
using Microsoft.AspNetCore.Mvc;

namespace A1.Controllers
{
    public class HistoryDetailsController : Controller
    {
        private readonly SaveData _context;

        public HistoryDetailsController(SaveData context)
        {
            _context = context;
        }

        public static List<Cart> cart = new List<Cart>();

        public IActionResult Details(int? id)
        {
            cart.Clear();
            //table
            var tr = _context.TrTable.Where(x => x.Id == id).FirstOrDefault();

            string[] str = tr.CartList.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries);

            foreach (var i in str)
            {
                var c = _context.CartTable.Where(x => x.Id == Convert.ToInt32(i)).FirstOrDefault();
                cart.Add(c);
            }

            ViewBag.time = tr.PaidTime;
            ViewBag.Amount = tr.GrandTotal;
            ViewBag.tax = tr.Tax;
            ViewBag.Username = tr.UserName;
            ViewBag.Address = tr.BillingAddress;
            ViewBag.TrID = tr.TransactionId;
            return View(cart);
        }
    }
}

A1/Controllers/MyHomePageController.cs
using A1.CreditCardFunction;
using A1.Data;
using A1.Models;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace A1.Controllers
{
    public class MyHomePageController : Controller
    {
        #region 全局变量
        private readonly DtoStripeSecrets _stripeSecrets;

        static DtoStripeSecrets stripeSecrets = new DtoStripeSecrets()
        {
            SecretKey = "sk_test_51LFrBPCDMjmOjphDkCD5knDL4oLcb1bb6XMIOHIZ3AizXlVnzdS6xcgVYbkxPTdg35VrT5Rd5xME04Cq5PoOt7D100pS55JR49",
            PublishableKey = "pk_test_51LFrBPCDMjmOjphDmhCWgsFP5QXCXxv0p1oFE0ySjBUHQ0CwKAeuxeCNEYl8gtkXo4NZsYTDiD8Hf0KPQKVUA2mJ00FWY79rOk"
        };

        public List<Models.Product> pd = new List<Models.Product>();

        public static List<Tr> tr = new List<Tr>();

        public List<Cart> cart = new List<Cart>();

        public static List<User> user = new List<User>();

        public static List<Master> Mas = new List<Master>();

        public static List<Comment> com = new List<Comment>();

        private static double Subtotal = 0;

        private static string CurrentTransactionId = "";

        private static string logincheng = "null";

        private readonly SaveData _context;

        public MyHomePageController(SaveData context)
        {
            _context = context;
        }

        #endregion

        #region 方法
        //主页
        public IActionResult Index()
        {
            ViewBag.background = MySettingController.Myback;
            ViewBag.loginchanges = logincheng;
            pd = _context.ProductTable.Where(x => x.Quantity >= 1).ToList();
            return View(pd);
        }

        //产品
        public IActionResult ProductPage(string filterType)
        {
            ViewBag.background = MySettingController.Myback;
            ViewBag.loginchanges = logincheng;
            if (filterType == "1")
            {
                pd = _context.ProductTable.OrderBy(x => x.Price).ToList();
                return View(pd);
            }
            else if (filterType == "2")
            {
                pd = _context.ProductTable.OrderByDescending(x => x.Price).ToList();
                return View(pd);
            }
            else if (filterType == "0")
            {
                pd = _context.ProductTable.Where(x => x.Quantity >= 1).ToList();
                return View(pd);
            }
            else
            {
                pd = _context.ProductTable.Where(x => x.Quantity >= 1).ToList();
                return View(pd);
            }
        }

        //搜寻产品
        [HttpPost, ActionName("ProductPage")]
        [ValidateAntiForgeryToken]
        public IActionResult ProductPagePOST(string search)
        {
            if (search == null)
            {
                TempData["error"] = "Can't Enter Empty Value";
                return RedirectToAction("ProductPage");
            }
            pd = _context.ProductTable.Where(x => x.Name.Contains(search)).ToList();
            return View(pd);
        }

        //注册
        public IActionResult SignUpPage()
        {
            MySettingController.Myback = "snow";
            logincheng = "null";
            return View();
        }

        //注册 信息
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SignUpPage(User user, string p1)
        {
            if (user != null)
            {
                if (user.UserName == null || user.Address == null || user.Email == null || user.AddressZip == null)
                {

                    return View(user);
                }

                if (user.AddressZip.Length > 5)
                {
                    TempData["error"] = "Address cannot exceed 5 digits.";
                    return View(user);
                }

                if (user.UserName.Length > 8)
                {
                    TempData["error"] = "Name cannot exceed 8 digits.";
                    return View(user);
                }

                bool b = int.TryParse(p1, out int pass);
                if (b == true)
                {
                    if (p1.Length < 6)
                    {
                        TempData["error"] = "Password must be more than 6 digits.";
                        return View(user);
                    }

                    var vx1 = _context.UserTable.Where(x => x.Email == user.Email).FirstOrDefault();
                    var vx2 = _context.UserTable.Where(x => x.Password == p1).FirstOrDefault();

                    if (vx1 != null)
                    {
                        TempData["error"] = "Please use another gmail.";
                        return View(user);
                    }
                    else if (vx2 != null)
                    {
                        TempData["error"] = "Please use another password.";
                        return View(user);
                    }

                    user.Password = p1;
                    user.CreateDate = DateTime.Now;
                    user.Hurl = "himg.png";
                    user.Money = 0;
                    _context.UserTable.Add(user);
                    _context.SaveChanges();
                    TempData["success"] = "Created Successfully";
                    return RedirectToAction("LoginPage");
                }
                else
                {
                    TempData["error"] = "Password can only enter numbers.";
                    return View(user);
                }
            }

            return View(user);
        }

        //登入
        public IActionResult LoginPage(string clear)
        {
            MySettingController.Myback = "snow";
            logincheng = "null";
            if (clear == "true")
            {
                user.Clear();
            }
            return View();
        }

        //登入 信息
        [HttpPost]
        public IActionResult LoginPage(string Email, string Password, string signout)
        {

            var vs = _context.UserTable.Where(x => x.Email == Email && x.Password == Password).FirstOrDefault();

            if (signout == "Sign Out")
            {
                logincheng = "null";
                var vv = user.FirstOrDefault();
                _context.SaveChanges();
                user.Clear();
                TempData["success"] = "Sign Out Success";
                return RedirectToAction("LoginPage");
            }

            if (Email == "Hoo9096844hwc" && Password == "084487")
            {
                logincheng = "null";
                user.Clear();
                return RedirectToAction("OldMaster");
            }

            if (vs != null)
            {
                user = _context.UserTable.Where(x => x.Email == Email && x.Password == Password).ToList();
                _context.SaveChanges();
                TempData["success"] = "Login Success";
                logincheng = "success";
                return RedirectToAction("WaitHistory", "Waiting");
            }
            else
            {
                logincheng = "null";
                TempData["error"] = "Login Failed";
                return RedirectToAction("LoginPage");
            }


        }

        //登出
        public IActionResult Signoutpage()
        {
            logincheng = "null";
            user.Clear();
            TempData["success"] = "Sign Out Success";
            return RedirectToAction("LoginPage");
        }

        //添加产品
        public IActionResult BuyPage(int? Id)
        {
            ViewBag.loginchanges = logincheng;
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = _context.ProductTable.Find(Id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //添加产品  进入  购物车里
        [HttpPost, ActionName("BuyPage")]
        [ValidateAntiForgeryToken]
        public IActionResult BuyPagePOST(int? id)
        {
            if (user.Count() == 0)
            {
                TempData["error"] = "Please Login";
                return RedirectToAction("LoginPage");
            }

            var o = _context.ProductTable.Find(id);
            if (o == null)
            {
                return NotFound();
            }

            var u = user.FirstOrDefault();
            var gm = _context.CartTable.Where(x => x.UserID == u.Id && x.Product_ID == o.Product_ID).FirstOrDefault();

            //加入购物车
            if (gm == null)
            {
                _context.CartTable.Add(new Cart()
                {
                    UserID = u.Id,
                    UserName = u.UserName,
                    Img = o.Img,
                    ProductName = o.Name,
                    Product_ID = o.Product_ID,
                    Quantity = 1,
                    LastQuantity = 1,
                    Product_Price = o.Price,
                    Buy = false
                });

                o.Quantity -= 1;
                o.BuyCount += 1;

            }
            else
            {
                if (gm.Buy == true)
                {
                    gm.Quantity += 1;
                    gm.LastQuantity = 1;
                    gm.Buy = false;
                }
                else if (gm.Buy == false)
                {
                    gm.Quantity += 1;
                    gm.LastQuantity += 1;
                    gm.Buy = false;
                }

                o.Quantity -= 1;
                o.BuyCount += 1;
            }

            _context.SaveChanges();

            TempData["success"] = "Add Success";
            return RedirectToAction("ShoppingCart");
        }

        //忘记密码
        public IActionResult ForgetPassword()
        {
            return View();
        }

        //更换密码
        [HttpPost]
        public IActionResult ForgetPassword(string Email, string p1)
        {

A1/Views/MyHomePage/AddProduct.cshtml
@{
	ViewData["Title"] = "AddProduct";
	Layout = "Master_layout";
}


<div class="mas_header last">

	<div class="bp">
	</div>

</div>


<div class="wrapper">
	<div class="registration_form mn">
		<div class="title t1">
			Create Form
		</div>

		<form action="~/MyHomePage/AddProduct" enctype="multipart/form-data" method="post">
			<div class="form_wrap v">
				<div class="input_grp">
					<div class="input_wrap">
						<label for="fname">Product Name</label>
						<input id="MyName" type="text" name="Name" placeholder="Enter Product Name" required>
					</div>
					<div class="input_wrap">
						<label for="lname">Quantity</label>
						<input class="pd" type="number" name="Quantity" placeholder="Quantity" required id="quantity">
					</div>
				</div>
				<div class="input_wrap">
					<label for="email">Video</label>
					<input type="text" name="src" placeholder="Only Youtube Src or Enter no" required id="video">
				</div>
				<div class="input_wrap">
					<label for="email">Product Image</label>
					<input type="file" name="Img" required id="fileimg">
				</div>
				<div class="input_wrap">
					<label for="email">Product Info</label>
					<input type="text" name="Info" placeholder="Enter Info" required id="info">
				</div>
				<div class="input_grp">
					<div class="input_wrap">
						<label for="fname">Price</label>
						<input class="pd" type="number" name="Price" placeholder="Enter Price" required id="price">
					</div>
					<div class="input_wrap">
						<label for="lname">DelPrice</label>
						<input class="pd" type="number" name="DelPrice" placeholder="Enter DelPrice" required id="delprice">
					</div>
				</div>
				<div class="input_wrap">
					<label>Category</label>
					<ul>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="Phone" class="input_radio" checked>
								<span>Phone</span>
							</label>
						</li>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="TV" class="input_radio">
								<span>TV</span>
							</label>
						</li>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="Earphone" class="input_radio" checked>
								<span>Earphone</span>
							</label>
						</li>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="Bicycle" class="input_radio">
								<span>Bicycle</span>
							</label>
						</li>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="Computer" class="input_radio" checked>
								<span>Computer</span>
							</label>
						</li>
					</ul>
				</div>
				<div class="input_wrap">
					<ul>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="Washer" class="input_radio" checked>
								<span>Washer</span>
							</label>
						</li>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="Refrigerator" class="input_radio">
								<span>Refrigerator</span>
							</label>
						</li>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="Pizza" class="input_radio" checked>
								<span>Pizza</span>
							</label>
						</li>
						<li>
							<label class="radio_wrap">
								<input type="radio" name="Category" value="Other" class="input_radio">
								<span>Other</span>
							</label>
						</li>
					</ul>
				</div>
				<div class="input_wrap">
					<input id="submitbtn" type="submit" value="Create Now" class="submit_btn" disabled />
				</div>
			</div>
		</form>
	</div>
</div>


<div class='move'>
	<div class='box'>
		<ul>
			<li class='list '>
				<a asp-controller="MyHomePage" asp-action="MasterHome" asp-route-id="@ViewBag.Mas_id">
					<span class='icon'><ion-icon name="home-outline"></ion-icon></span>
					<span class='text'>Home</span>
				</a>
			</li>
			<li class='list '>
				<a asp-controller="MyHomePage" asp-action="MasterUser">
					<span class='icon'><ion-icon name="person-outline"></ion-icon></span>
					<span class='text'>User</span>
				</a>
			</li>
			<li asp-controller="MyHomePage" asp-action="MasterProduct">
				<a asp-controller="MyHomePage" asp-action="MasterProduct">
					<span class='icon'><ion-icon name="cube"></ion-icon></span>
					<span class='text'>Product</span>
				</a>
			</li>
			<li class='list active'>
				<a asp-controller="MyHomePage" asp-action="AddPage">
					<span class='icon'><ion-icon name="add-circle-outline"></ion-icon></span>
					<span class='text'>Add</span>
				</a>
			</li>
			<li class='list'>
				<a asp-controller="MyHomePage" asp-action="LoginPage" asp-route-clear="true">
					<span class='icon'><ion-icon name="log-out-outline"></ion-icon></span>
					<span class='text'>Sign Out</span>
				</a>
			</li>
			<div class='info'></div>
		</ul>
	</div>
</div>

<script>

	var MyName = document.getElementById("MyName")
	var quantity = document.getElementById("quantity")
	var video = document.getElementById("video")
	var fileimg = document.getElementById("fileimg")
	var info = document.getElementById("info")
	var price = document.getElementById("price")
	var delprice = document.getElementById("delprice")

	function Checkbtn(){
		var MyName = document.getElementById("MyName").value
		var quantity = document.getElementById("quantity").value
		var video = document.getElementById("video").value
		var fileimg = document.getElementById("fileimg").value
		var info = document.getElementById("info").value
		var price = document.getElementById("price").value
		var delprice = document.getElementById("delprice").value

		var checkVideo;
		if(video.toLowerCase() == "no" || video.indexOf("https://www.youtube.com") != -1){
			 checkVideo = "ya";
		}else{
			 checkVideo = "null";
		}

		console.log("CC  " + checkVideo)

		if(MyName == "" || quantity == "" || video == "" || checkVideo == "null"  || fileimg == "" || info == "" || price == ""|| delprice == "" || parseInt(price) > parseInt(delprice)){
			document.getElementById("submitbtn").disabled = true;
		}else{
			console.log("走过2")
			document.getElementById("submitbtn").disabled = false;
		}
	}

	MyName.onkeyup = function(){
		if(this.value.length >= 1){
			document.getElementById("submitbtn").disabled = false;
			Checkbtn()
		}else{
			document.getElementById("submitbtn").disabled = true;
			Checkbtn()
		}
	}

	quantity.onkeyup = function(){
		if(this.value >= 1){
			document.getElementById("submitbtn").disabled = false;
			Checkbtn()
		}else{
			document.getElementById("submitbtn").disabled = true;
		}
	}

	video.onkeyup = function(){
		if(this.value.toLowerCase() == "no" || this.value.indexOf("https://www.youtube.com") != -1){
			document.getElementById("submitbtn").disabled = false;
			console.log("Video走过1")
			Checkbtn()
		}else{
			document.getElementById("submitbtn").disabled = true;
			console.log("Video走过1   null")
			Checkbtn()

		}
	}

	fileimg.onchange = function(){
		if(this.value == '') {
			document.getElementById("submitbtn").disabled = true;
		}else {
			document.getElementById("submitbtn").disabled = false;
			Checkbtn()
		}
	}

	info.onkeyup = function(){
		if(this.value.length >= 1){
			document.getElementById("submitbtn").disabled = false;
			Checkbtn()
		}else{
			document.getElementById("submitbtn").disabled = true;
		}
	}

	price.onkeyup = function(){
		if(this.value >= 1){
			document.getElementById("submitbtn").disabled = false;
			Checkbtn()
		}else{
			document.getElementById("submitbtn").disabled = true;
		}
	}

	delprice.onkeyup = function(){
		var price2 = document.getElementById("price")
		if(parseInt(this.value) >= parseInt(price2.value)){
			console.log("MydelPrice走过1")
			document.getElementById("submitbtn").disabled = false;
			Checkbtn()
		}else{
			document.getElementById("submitbtn").disabled = true;
		}
	}



</script>

A1/Views/MyHomePage/CardNumb.cshtml
@model A1.CreditCardFunction.CreditCard

@{
	ViewData["Title"] = "CardNumb";
	Layout = "Card_Layout";
}

<div class="row divPay">
	<div class="column c1">
		<h2 style="margin-bottom: 10px;">Summary</h2>

		<img src="https://images.pexels.com/photos/556663/pexels-photo-556663.jpeg" class="imgResumen">

		<div class="totalTxt">
			<h3 style="color: #a9abae">Total</h3>
			<h3 class="total" style="color:#F2994A;">RM @ViewBag.total</h3>
			<a class="back" asp-controller="MyHomePage" asp-action="OuttoCardNumb">Back</a>
		</div>



	</div>
	<div class="column c2">

		<h2 style="margin-bottom: 10px;">Payment</h2>

		<div class="card" id="divCard">
			<div class='card-content'>
				<img style="display: none" id="imgFranchise" class="logoFranquicia">
				<div class="infoTarjeta">
					<h5>Card Number</h5>
					<h6 id="cardNumber">0000 0000 0000 0000</h6>
					<h5>Expiration<span class="cvvStyle">CVV</span></h5>
					<h6><span id="cardMonth">00</span> / <span id="cardYear">0000</span><span class="cvvStyle2" id="cardCVV">000</span></h6>
				</div>
			</div>
		</div>

		<br>
		<form action="~/MyHomePage/CardNumb?total=@ViewBag.total" method="post">

			<div style="width: 100%;margin: auto;">
				<div style="width: 50%;display: inline-block;"><b>Cardholder</b></div>
				<input asp-for="Name" type="text" id="pagarTarjetaTit" placeholder="Cardholder" maxlength="16" style="width: 100%">
			</div>

			<div style="width: 100%;margin: auto;">
				<div style="width: 50%;display: inline-block;"><b>Card Number</b></div>
				<input asp-for="Number" type="text" id="pagarTarjetaNum" placeholder="Eg. 1111222233334444" style="width: 100%" maxlength="16" onkeyup="showCN(this.value)">
			</div>

			<div style="width: 100%;margin: auto;">
				<div style="width: 50%;display: inline-block;"><b>Email</b></div>
				<input asp-for="Email" type="email" id="mygmail" placeholder="Email" style="width: 100%">
			</div>

			<div style="width: 100%;margin: auto;">
				<div style="width: 50%;display: inline-block;margin-bottom:1rem;"><b>Expiration</b></div>

				<div class="row">
					<div class="column">
						<div style="width: 100%;display: inline-block;"><b>Month</b></div>
						<input asp-for="ExpMonth" type="number" id="pagarTarjetaMes" placeholder="Eg. 03" min="01" max="12" style="width: 80%" oninput="showCE()">
					</div>
					<div class="column">
						<div style="width: 100%;display: inline-block;"><b>Year</b></div>
						<input asp-for="ExpYear" type="number" id="pagarTarjetaAno" placeholder="Eg. 2024" min="2020" max="2100" style="width: 80%" oninput="showCE()">
					</div>
				</div>
			</div>

			<div style="width: 100%;margin: auto;">
				<div style="width: 50%;display: inline-block;"><b>CVV</b></div>
				<input asp-for="Cvc" type="number" id="pagarTarjetaCVV" placeholder="Eg. 123" min="001" max="9999" style="width: 50%" oninput="showCV()">
			</div>

			<button type="submit" title="Make payment">Make payment</button>
		</form>


	</div>
</div>

<br>



@*<p>Made by: <a href="https://twitter.com/ThomRodrigu" target="_blank">Thomas Rodríguez</a> | Inspired in <a href="https://codepen.io/syedakhtar/pen/BVXEPq" target="_blank">this pen</a></p>

*@

A1/Views/MyHomePage/History.cshtml
@model IEnumerable<Tr>

@{
	ViewData["Title"] = "History";
}

@{
	int num = 1;
}

@{
	ViewBag.table_pd = "table-dark table-hover";
	if (@ViewBag.background == "black")
	{
		ViewBag.h1 = "H_right_black";
		ViewBag.table_pd = "table-primary";
	}
}

<div class="m_box" style="@ViewBag.display">
	<div class="m2_box">
		<div class="m3_box">
			<div class="icon">
				<a asp-controller="MyHomePage" asp-action="History" asp-route-block="none"><i class="fas fa-times"></i></a>
			</div>
			<div class="context">
				<h1 style="color:black;">Recharge</h1>
			</div>

			<div class="info">
				<form action="~/MyHomePage/AddMoney" method="post">
					<div class="input-group mb-3 sx">
						<span class="input-group-text" id="basic-addon1"><i class="fas fa-dollar-sign"></i></span>
						<input type="number" name="money" class="form-control" placeholder="Money" aria-label="Username" aria-describedby="basic-addon1">
					</div>

					<div class="input-group mb-3 sx3">
						<span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-credit-card"></i></span>
						<input maxlength="16" type="text" name="card" class="form-control" placeholder="Card Number" aria-label="Username" aria-describedby="basic-addon1">
					</div>

					<div class="input-group mb-3 sx2">
						<span class="input-group-text" id="basic-addon1"><i class="fas fa-lock"></i></span>
						<input type="password" name="n1" class="form-control" placeholder="You Password" aria-label="Username" aria-describedby="basic-addon1">
					</div>
					<input type="submit" class="btn btn-outline-dark py-3 px-5 offset-md-3 sbtn" value="Confirm" />
				</form>
			</div>
		</div>
	</div>
</div>

<div class="cart_title">
	<h1>Purchase History</h1>
</div>

<div class='navbar__nav'>
</div>

<div class='H_container'>


	<section class='H_left'>
		<a class="name" asp-controller="MyHomePage" asp-action="Information" asp-route-id="@ViewBag.ID">
			<h3 class="h_3">@ViewBag.Name</h3>
		</a>

		<div class="user_icon">

			<form action="~/MyHomePage/History" enctype="multipart/form-data" method="post">

				<input id="myIcon" type="file" name="file" onchange="chooseImg(this)">
				<i class="fa-solid fa-user"></i>
				<img id="img" src="~/Img/TX/@ViewBag.Hurl" onclick="myIcon.click()">
				<input id="sub" type="submit" value="Update Avatar">

			</form>

			<form action="~/MyHomePage/LoginPage" method="post">
				<input id="so" type="submit" value="Sign Out" name="signout">
			</form>

		</div>

		<div class="RM">
			<div class="mo2">
				<a asp-controller="MyHomePage" asp-action="History" asp-route-block="block"><p class="icon"><i style="color: white;" class="fas fa-plus-circle"></i></p></a>
				<p class="mo">RM <span>@(ViewBag.money.ToString("0.00"))</span></p>
			</div>
		</div>

	</section>

	<section class='H_right @ViewBag.h1'>
		<div class="cart_box">
			<table class="table @ViewBag.table_pd t2">
				<thead>
					<tr>
						<th>
							No.
						</th>
						<th>
							Total Price
						</th>
						<th>
							PaidTime
						</th>
						<th>
							View Details
						</th>
					</tr>
				</thead>

				<tbody>
					@foreach (var i in Model)
					{
						if (@i.Id == 0)
						{
							<tr>
								<td>
									<h6>No Data</h6>
								</td>
								<td>
									<h6>No Data</h6>
								</td>
								<td>
									<h6>No Data</h6>
								</td>
								<td>
									<h6>No Data</h6>
								</td>
							</tr>
						}
						else
						{
							if (@i.PaidTime == "Not Yet Update")
							{
								<tr>
									<td>
										@(num++)
									</td>
									<td>
										<h6>RM @i.GrandTotal</h6>
									</td>
									<td>
										<h6>@i.PaidTime</h6>
									</td>
									<td>
									</td>
								</tr>
							}
							else
							{
								<tr>
									<td>
										@(num++)
									</td>
									<td>
										<h6>RM @i.GrandTotal</h6>
									</td>
									<td>
										<h6>@i.PaidTime</h6>
									</td>
									<td>
										<a class="view" asp-controller="HistoryDetails" asp-action="Details" asp-route-id="@i.Id">View</a>
									</td>
								</tr>
							}


						}
					}
				</tbody>

			</table>
		</div>
	</section>
</div>

<script>
	document.getElementById("history").style.background = "cornflowerblue"
</script>

A1/Views/MyHomePage/Information.cshtml
@model IEnumerable<User>

@{
	ViewData["Title"] = "Information";
	Layout = "Information_Layout";
}


<div class="i_header">

	<div class="bp">
	</div>

</div>

@foreach (var i in Model)
{
	<div class="main_box">
		<div class="box">
			<div class="left">
				<img src="~/Img/TX/@i.Hurl" alt="" />
			</div>
			<div class="right">
				<div class="header">
					<h6>@i.UserName</h6>
				</div>
				<hr />
				<div class="gmail">
					<h6>@i.Email</h6>
				</div>

				<div class="m_box">
					<div class="m_left">
						<p><span class="s1">Gender</span><span class="s2">@i.Gender</span></p>
						<p><span class="s1">Address</span><span class="s2">@i.Address</span></p>
						<p><span class="s1">AddressZIP</span><span class="s2">@i.AddressZip</span></p>
						<p><span class="s1">CreateDate</span><span class="s2">@i.CreateDate</span></p>
					</div>
					<div class="m_right">
						<p><span class="s1">Role</span><span class="s2">@i.Role</span></p>
						<p><span class="s1">City</span><span class="s2">@i.City</span></p>
						<p><span class="s1">Money</span><span class="s2">RM @(i.Money.ToString("0.00"))</span></p>
						<p><span class="s1">Total Recharge</span><span class="s2">RM @(i.OutMoney.ToString("0.00"))</span></p>
					</div>
				</div>


				<div class="out">
					<a asp-controller="MyHomePage" asp-action="History">Back</a>
				</div>

			</div>
		</div>
	</div>
}

A1/Views/MyHomePage/OldMaster.cshtml
@model IEnumerable<Master>

@{
	ViewData["Title"] = "OldMaster";
	Layout = "OldMaster_Layout";
}


@{
	int num = 1;
}


<section>
	<div class='box'>
		<h3>Welcome Master</h3>

		@foreach (var i in Model)
		{
			<a asp-controller="MyHomePage" asp-action="MasterHome" asp-route-id="@i.Id" class='list'>
				<div class='imgBx'>
					<img src="~/@i.Img" alt=''>
				</div>
				<div class='content'>
					<h2 class='rank'><small>#</small>@(num++)</h2>
					<h4>@i.Info</h4>
					<p style="font-size:0.5rem;">@i.Mas</p>
				</div>
			</a>
		}

	</div>
</section>